version: '3'

services:
  front-end:
    build: 
      # Specify the location of where all the files are
      context: .
      # Specify the custom created docker file.
      dockerfile: ./Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /usr/app/node_modules
      - .:/usr/app

  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/app/node_modules
      - .:/usr/app
    command: ["npm", "run", "test"]  